# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: minestore new
email: contato@minestore.com.br
baseurl: "/minestore-new"
url: "http://yourdomain.com"
sass:
  load_paths:
    - assets/_sass
    - assets/_components/foundation/scss
    - assets/_components/motion-ui/src

# Build settings
markdown: kramdown
