# Site settings
title: minestore new
email: contato@minestore.com.br
baseurl: "/minestore-new"
url: "http://yourdomain.com"
sass:
  load_paths:
    - assets/_sass

# Build settings
markdown: kramdown
permalink: /:title
exclude :
  - node_modules
