# Site settings
title: minestore new
email: contato@minestore.com.br
baseurl: "/landing-2016"
url: "http://yourdomain.com"
sass:
  load_paths:
    - assets/_sass

# Build settings
markdown: kramdown
permalink: /:title
exclude :
  - bower.json
  - node_modules
  - package.json
  - Rakefile
